### ISSUE TITLE
Rename gin?

### ISSUE THREAD

**Issue by Timmmm** [codegangsta/gin#117]
This is just a suggestion but it's a bit confusing that there are two Go web development things called gin.

**Comment by stevenventimiglia** [comment]
I agree.  Gin Gonic comes to mind.
[https://gin-gonic.github.io/gin/](https://gin-gonic.github.io/gin/)

**Comment by ibash** [comment]
What do you think of the name `bin`?

**Comment by mehmetkose** [comment]
Agree! Bin is great!

**Comment by JoakimSoderberg** [comment]
Hmmm bin is a bit generic isn't it? :)

```
/usr/bin/bin
```

Some name suggestions:

- gofresh
- gore
- gorestart
- goproxythatrestartsstuff
- goin (as in keep goin)

**Comment by ibash** [comment]
ls for listening server? (Because it listens to changes)

**Comment by mehmetkose** [comment]
ls already a thing in the bash bro.
I think nobody is maintaining this project anymore.

**Comment by benbotwin** [comment]
You could name it `guild`

go + build

... it's an awful pun :)
