### ISSUE TITLE
Arguments to the app

### ISSUE THREAD

**Issue by dahankzter** [codegangsta/gin#14]
I have an app that takes an argument to a config file. Is there already a way to pass it in that I have missed or could we add it somehow?

**Comment by pferdefleisch** [comment]
I don't know if this works for flag or named arguments (like -config) but I have an app that runs like this normally

`myapp serve`

and gin takes your arguments [here](https://github.com/codegangsta/gin/blob/master/main.go#L97) and forwards them to the compiled binary [here](https://github.com/codegangsta/gin/blob/master/lib/runner.go#L96)

So this works for me from my example above

`gin serve`

I would assume in your (possible) case

`gin -config=./config.yml`

would probably work too but I haven't tested it

**Comment by zippoxer** [comment]
@pferdefleisch 

The above does not work for me.

**Comment by psucodervn** [comment]
Hi, is there any workaround for this issue?

**Comment by itachiRedhair** [comment]
Not sure if the above commit addresses this issue, but I still face the same problem.
