### ISSUE TITLE
flag provided but not defined: -immediate

### ISSUE THREAD

**Issue by annaelizabeth2019** [codegangsta/gin#158]
Attempted these commands:
gin run main.go --immediate
gin run main.go -i
gin -i run main.go
gin --immediate run main.go 

Returns: 
Incorrect Usage: flag provided but not defined: -immediate

In gin --help:
   --immediate, -i               run the server immediately after it's built [$GIN_IMMEDIATE]

**Comment by PedroS11** [comment]
I tried in my recent GO project this
`gin -i run main.go`

and everything worked great, try the last version of gin
