### ISSUE TITLE
Strange behavior when reloading in a Docker container 

### ISSUE THREAD

**Issue by crsmithdev** [codegangsta/gin#72]
I see this strange behavior when I run `gin` in a docker container.  After making a change, the app will start reloading continuously, often not stopping for 10, 20+ attempts.  This does not occur when run in a local environment.

**Comment by crsmithdev** [comment]
I *think* this was related to clock skew between my laptop and vagrant.

**Comment by drgomesp** [comment]
I had the same issue. For those running docker machine, this should do the trick:

```bash
docker-machine ssh default 'sudo ntpclient -s -h pool.ntp.org'
```
